# Generated by Django 4.1.7 on 2023-02-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_date_of_death_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
